<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="03-config-relatorio"
    errors="0" failures="1" hostname="" id="" package="03-config-relatorio" skipped="0"
    tests="1" time="20.80" timestamp="Fri, 30 Nov 2018 20:28:06 GMT">
  
    <testcase name="default e2e tests" classname="03-config-relatorio" time="20.80" assertions="3">

    

      <failure message="Timed out while waiting for element &lt;#contRel&gt; to be present for 10000 milliseconds.">    at Object.default e2e tests (C:\Users\Adriano\git\FlorDAcucena\sistema\tests\e2e\specs\03-config-relatorio.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:61:11)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
